### ISSUE TITLE
Weekly Leetcode Challenge Questions

### ISSUE THREAD

**Issue by n-bakken** [n-bakken/gdsc-website#7]
Not necessary if we run out of time, just nice to have
Similar to how "news" changes regularly on other websites, this could be something that is advertised to our members as something to tackle. 
It could randomly choose an easy question from leetcode's question bank, unless there's some way to integrate leetcode into the site?

**Comment by HowardLee134** [comment]
We could do that, just kinda confuse which section should we put that into

**Comment by n-bakken** [comment]
fixed with last PR I did! forgot to link the issue.
